### ISSUE TITLE
List of facts

### ISSUE THREAD

**Issue by LisanneArdern** [LisanneArdern/dog-facts-app#1]
## Value statement (User Story)
As a **user** 
I need **a list of dog facts** 
so that **I can learn more about dogs** 

## Description (Text, Scribble, Wireframe, Design)
![List-of-facts](https://user-images.githubusercontent.com/82395516/132221449-041b5cf1-3919-4da3-9441-fd0e9f437b58.png)

## Acceptance criteria
- [ ] Sorted alphabetically ascending

## Tasks
- [x] Create feature branch
- [x] Save a few crops from [Dog facts API](https://dog-facts-api.herokuapp.com/api/v1/resources/dogs/all) as json 
- [x] Build list item component
- [x] Write test for component
- [x] Add list to App
- [x] Add global styles

## Complexity 
low
