### ISSUE TITLE
Integration of API

### ISSUE THREAD

**Issue by LisanneArdern** [LisanneArdern/dog-facts-app#3]
## Value statement (User Story)
As a **user** 
I need ** an integrated API** 
so that **I have access to more dog facts** 

## Acceptance criteria
- [ ] 

## Tasks
- [ ] Create feature branch
- [ ] Integrate API from [Dog facts API](https://dog-facts-api.herokuapp.com/api/v1/resources/dogs/all) 
- [ ] Update component and App.tsx
