### ISSUE TITLE
Add shuffle function

### ISSUE THREAD

**Issue by LisanneArdern** [LisanneArdern/dog-facts-app#4]
## Value statement (User Story)
As a **user** 
I need ** shuffle function** 
so that **random facts can be displayer** 

## Description (Text, Scribble, Wireframe, Design)
![Random-facts](https://user-images.githubusercontent.com/82395516/132995289-9513e146-362d-4b19-8694-2485ab4bdcee.png)

## Acceptance criteria
- [ ] Button that shuffles displayed fact

## Tasks
- [ ] Create feature branch
- [ ] Create Button component
- [ ] Write test for new component
- [ ] Update App.tsx
